### PR TITLE
chess app stored request add units

### PR DESCRIPTION
**Pull request by tcreamer1**
Requires:
```
stored_requests:
  filesystem: true
```

### CODE REVIEW

**Review by dbruneau — COMMENTED** [review]
Just checking, but is it intentional that `in_article_ios.json` and `play_screen_ios.json` are identical to `game_over_ios.json`?

**Comment by tcreamer1** [comment]
At the moment they are the same since they have the same sizes, but they are 3 different ad units that will be called from the app. If any of them should need changed, the app won't need to be updated, we can adjust from these files.

**Comment by dbruneau** [comment]
> At the moment they are the same since they have the same sizes, but they are 3 different ad units that will be called from the app. If any of them should need changed, the app won't need to be updated, we can adjust from these files.

If the ad units are different, should the `id` values in their JSON differ, or is that not appropriate in this case?

**Comment by tcreamer1** [comment]
I don't know if it technically makes a difference, however I do think it should be consistent. Thanks for catching that!

**Review by dbruneau — APPROVED** [review]
LGTM!

**Comment by dbruneau** [comment]
@tcreamer1 This should now be on `prebid-server-dev`.  The Heroku app is set up to automatically deploy after merging into `develop`.

I've also set the required environment variable there.  The command to do that from the `heroku` CLI is

````heroku config:set -a prebid-server-dev PBS_STORED_REQUESTS_FILESYSTEM=true````

In general, the key name is `PBS_` plus the up-cased, fully qualified name of the variable.

**Comment by tcreamer1** [comment]
@dbruneau Thanks so much!

**Pull request merged**
